version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: autocontent-pro-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: autocontent-pro-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped

  wa-worker:
    build:
      context: .
      dockerfile: apps/wa-worker/Dockerfile
    container_name: autocontent-pro-wa-worker
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WA_WORKER_CONCURRENCY=3
    volumes:
      - wa_sessions:/app/.wwebjs_auth
    depends_on:
      - redis
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: autocontent-pro-web
    ports:
      - "4200:80"
    restart: unless-stopped

volumes:
  redis_data:
  wa_sessions:
